parameters:
    astina_translation.loader.class: Astina\Bundle\TranslationBundle\Loader\DoctrineLoader

services:

    astina_translation.loader:
        class: %astina_translation.loader.class%
        arguments: [ @astina_translation.repository.translation ]
        tags:
            - { name: translation.loader, alias: db }

    astina_translation.repository.translation:
        class: Doctrine\ORM\EntityRepository
        factory_service: doctrine
        factory_method: getRepository
        arguments: [ AstinaTranslationBundle:Translation ]